### ISSUE TITLE
At the end of loop.

### ISSUE THREAD

**Issue by KhantMin-coder** [JaysQubeXon/react-lottie-hook-demo#4]
Hi.
I don't know you guys are controlling the state but,

if I set `loop : false` . Isn't it normal to set the state of animation to `stopped` at the end of the loop.
From what i observe.The event is still on `playing`  state.

**Comment by JaysQubeXon** [comment]
@KhantMin-coder thank you for reporting this. Unfortunately, this issue was opened on a demo repository, you will need to open the issue on the actual library repository.
